### ISSUE TITLE
Issue on CentOS 7

### ISSUE THREAD

**Issue by lyderic** [classicsc/syncthingmanager#3]
Hi,

I get the following when trying to run a device list:

<pre>
[lyderic@cube ~]$ stman device list
Traceback (most recent call last):
  File "/usr/bin/stman", line 9, in <module>
    load_entry_point('syncthingmanager==0.1.0', 'console_scripts', 'stman')()
  File "/usr/lib/python3.4/site-packages/syncthingmanager/__init__.py", line 810, in main
    st._device_list()
  File "/usr/lib/python3.4/site-packages/syncthingmanager/__init__.py", line 471, in _device_list
    status = self.system.status()
  File "/usr/lib/python3.4/site-packages/syncthing/__init__.py", line 515, in status
    resp = keys_to_datetime(resp, 'startTime')
  File "/usr/lib/python3.4/site-packages/syncthing/__init__.py", line 125, in keys_to_datetime
    obj[k] = parse_datetime(v)
  File "/usr/lib/python3.4/site-packages/syncthing/__init__.py", line 79, in parse_datetime
    obj = datetime.strptime(s[0:26], date_format)
  File "/usr/lib64/python3.4/_strptime.py", line 507, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib64/python3.4/_strptime.py", line 347, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: +01
</pre>

I am running python 3.4 on CentOS 7. I installed syncthingmanager following the instructions.

My versions:

<pre>
[lyderic@cube ~]$ syncthing --version
syncthing v0.14.26 "Dysprosium Dragonfly" (go1.8 linux-amd64) jenkins@build.syncthing.net 2017-03-23 11:04:35 UTC

[lyderic@cube ~]$ pip3 --version
pip 9.0.1 from /usr/lib/python3.4/site-packages (python 3.4)

[lyderic@cube ~]$ python3 --version
Python 3.4.5

[lyderic@cube ~]$ cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 

[lyderic@cube ~]$ uname -a
Linux cube.lyderic.net 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

</pre>

My config file:

<pre>
[lyderic@cube ~]$ cat ~/.config/syncthingmanager/syncthingmanager.conf 
[DEFAULT]
name = localhost

[localhost]
apikey = JFUS.....
hostname = localhost
port = 8384
</pre>

Thanks for any help,

Lyderic

**Comment by classicsc** [comment]
Hi Lyderic
I haven't been able to reproduce the issue at this point. For comparison, could you do the following?
```
[sam@sam-pc ~]$ python3
Python 3.6.0 (default, Jan 16 2017, 12:12:55) 
[GCC 6.3.1 20170109] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import syncthing
>>> s = syncthing.Syncthing('YOUR_API_KEY', port=YOUR_GUI_PORT)
>>> s.system.get('status')['startTime']
'2017-04-18T14:08:41.03238611-07:00'
```
Thanks

**Comment by lyderic** [comment]
Hi Samuel,

Many thanks for looking at this.

Here you are:

<pre>
[lyderic@cube ~]$ python3
Python 3.4.5 (default, Nov  9 2016, 16:24:59) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import syncthing
>>> s = syncthing.Syncthing('JFUSxxxxxxxxxx', port=8384)
>>> s.system.get('status')['startTime']
'2017-04-19T10:04:13.698+01:00'
</pre>

**Comment by classicsc** [comment]
Thanks for the info, I've been too busy to look at it. Looks like your Syncthing is giving the startTime string in a format that the Python datetime library can't handle. Specifically, it may be giving the microsecond without zero-padding (698 in the above output should probably be 00000698 or 69800000).

My suggestion for now would be to install the latest version of Syncthing and try it again. If that doesn't work, there may be an issue somewhere. FWIW, all my Syncthing instances appear to be giving startTime in the expected format.

**Comment by mhaffner** [comment]
@lyderic  Did you start syncthing? I know that this is really basic, but I was getting errors as well, and I didn't really think about it since I always enable Syncthing to start on boot on my other machines.

**Comment by classicsc** [comment]
@mhaffner Always worth checking, but I doubt that is the issue here. If the API wasn't up then we wouldn't be getting startTime at all.

**Comment by lyderic** [comment]
Thanks for your answers / suggestions.

1. @mhaffner  I am sure I am running syncthing, as for one, the GUI is available.

2. @classicsc I am running the latest syncthing 0.14.28 and I still have the issue :-(

If I get the startTime directly from the 'rest/system/status' REST endpoint (with curl), I get:
"startTime": "2017-05-16T20:05:16.**731**+01:00"

Please note that only 3 digits are provided after the decimal point. This is specific to RedHat (CentOS) Linux. On Ubuntu, I get **9** digits:
"startTime": "2017-05-24T14:20:20.**969692135**+01:00",

You, it seems, get **8** digits. From what you provide above, on April 19:
'2017-04-18T14:08:41.**03238611**-07:00'

Can it be that your program always expects 8 digits to parse? If yes, then a fix could be to cut the first 3 digits provided and then only always parse 3 digits...

Many thanks for your time.
L.

**Comment by classicsc** [comment]
Alright, thanks for the confirmation. I still can't reproduce the issue on CentOS (same version and platform), which makes it difficult to figure out exactly what is happening.

One fix would involve the [python-syncthing](https://github.com/blakev/python-syncthing) package, specifically reworking the `parse_datetime` method. Similar to what you described, we could use a regular expression to parse the timestamp for its components, which is more flexible than the current method of taking substrings. For example:
```
syncthing_datetime_re = re.compile(r'(?P<year>\d{4})-(?P<month>\d\d)-(?P<day>\d\d)'
             r'T(?P<hour>\d\d):(?P<minute>\d\d):(?P<second>\d\d)(\.0*(?P<fsec>\d{1,6})\d*)?'
             r'((?P<offset_direction>\+|\-)(?P<offset_hour>\d\d):(?P<offset_minute>\d\d))?')
```

Where are you getting Syncthing? I use the tgz from GitHub and my own systemd units, but if you're using a package or building locally, that could help with reproducing the behaviour.

**Comment by lyderic** [comment]
I get syncthing from https://syncthing.net/. I simply download what they offer on the front page there. I don't compile it myself.

Now I have had a look at another CentOS machine and I get **9** digits indeed!
"startTime": "2017-05-16T15:56:02.**148356688**+01:00"

On a Debian Jessie machine, I also get **9** digits:
"startTime": "2017-05-16T05:03:00.**568656459**-04:00"

On a Mac, also **9** digits:
"startTime": "2017-05-28T08:19:39.**053928488**+01:00",

So, after closer inspection, the 3 digits are showing up on only **one** machine, it seems. The only thing this machine has different as far as I can tell is that it has an AMD CPU whereas the others run Intel...

Anyway, with a combination of _curl_'ing the REST API and hacking python-syncthing, I will manage to do what I need. What we have established is that your program is functioning correctly and then I guess this bug report can be closed.

Thanks a lot.
